//tealium universal tag - utag.74 ut4.0.201902221405, Copyright 2019 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={'view':1,'link':1};u.initialized=false;u.scriptrequested=false;u.queue=[];u.map={};u.extend=[];u.send=function(a,b){if(u.ev[a]||typeof u.ev.all!="undefined"){var c,d,e,f;u.data={"base_url":"//munchkin.marketo.net/munchkin.js","acct":"142-UEL-347","wsInfo":"","init":{},"view":{url:document.URL},"click":{},"lead":{}};for(d in utag.loader.GV(u.map)){if(typeof b[d]!=="undefined"&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(e[f].indexOf("init.")===0){u.data.init[e[f].substr(5)]=b[d];u.data.idata=!0;}else if(e[f].indexOf("view.")===0){u.data.view[e[f].substr(5)]=b[d];}else if(e[f].indexOf("click.")===0){u.data.click[e[f].substr(6)]=b[d];}else if(e[f].indexOf("lead.")===0){u.data.lead[e[f].substr(5)]=b[d];}else{u.data[e[f]]=b[d];}}}}
u.loader_cb=function(a,b,c){if(a==="link"||u.data.event_type==="clickLink"){Munchkin.munchkinFunction("clickLink",u.data.click);}
if(!u.initialized){u.initialized=true;if(u.data.wsInfo){u.data.init.wsInfo=u.data.wsInfo;u.data.idata=!0;}
if(!u.data.idata){Munchkin.init(u.data.acct);}else{Munchkin.init(u.data.acct,u.data.init);}}else{Munchkin.munchkinFunction('visitWebPage',u.data.view);}
if(u.data.event_type==="associateLead"){Munchkin.munchkinFunction(u.data.event_type,u.data.lead);}};u.callBack=function(){var data={};while(data=u.queue.shift()){u.data=data.data;u.loader_cb(data.a,data.b,data.c);}};if(u.initialized){u.loader_cb(a,b,c);}else{u.queue.push({"data":u.data,"a":a,"b":b,"c":c});if(!u.scriptrequested){u.scriptrequested=true;u.loader({"type":"script","src":u.data.base_url,"cb":u.callBack,"loc":"script","id":'utag_74'});}}
}};utag.o[loader].loader.LOAD(id);})('74','here.herecomcorporate');}catch(error){utag.DB(error);}
